"""
Summary Exporter Module
File: backend/exporter.py
Description: Export summaries to various formats
"""

from fpdf import FPDF
from datetime import datetime
import re


def _safe(text: str) -> str:
    """Strip emojis and non-latin-1 chars so Arial never chokes."""
    emoji_pat = re.compile(
        "[\U00010000-\U0010FFFF"
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002700-\U000027BF"
        "\U0000FE00-\U0000FE0F"
        "\U00002600-\U000026FF"
        "]+",
        flags=re.UNICODE,
    )
    text = emoji_pat.sub("", str(text))
    return text.encode("latin-1", errors="ignore").decode("latin-1").strip()


class SummaryExporter:
    """Export summaries to different formats"""

    @staticmethod
    def create_pdf(summary_text, title="Summary", summary_type="", metadata=None):
        """
        Create PDF file from summary text

        Args:
            summary_text (str): Summary content
            title (str): Document title
            summary_type (str): Type of summary
            metadata (dict): Additional metadata

        Returns:
            bytes: PDF file content
        """
        MARGIN = 20
        pdf = FPDF()
        pdf.set_margins(left=MARGIN, top=MARGIN, right=MARGIN)
        pdf.set_auto_page_break(auto=True, margin=MARGIN)
        pdf.add_page()

        # Usable width after margins
        w = pdf.w - 2 * MARGIN

        # Header
        pdf.set_font("Helvetica", 'B', 16)
        pdf.cell(w, 10, _safe("AI-Generated Summary"), align='C')
        pdf.ln(14)

        # Summary type
        if summary_type:
            pdf.set_font("Helvetica", 'I', 11)
            pdf.cell(w, 8, _safe(f"Type: {summary_type}"), align='C')
            pdf.ln(12)

        # Document title
        pdf.set_font("Helvetica", 'B', 11)
        pdf.cell(w, 8, _safe(title))
        pdf.ln(12)

        # Metadata
        if metadata:
            pdf.set_font("Helvetica", 'I', 9)
            if 'model' in metadata:
                pdf.cell(w, 6, _safe(f"AI Model: {metadata['model']}"))
                pdf.ln(7)
            if 'date' in metadata:
                pdf.cell(w, 6, _safe(f"Generated: {metadata['date']}"))
                pdf.ln(7)
            if 'compression' in metadata:
                pdf.cell(w, 6, _safe(f"Compression Ratio: {metadata['compression']:.1f}%"))
                pdf.ln(7)
            pdf.ln(4)

        # Divider
        pdf.set_draw_color(102, 126, 234)
        pdf.line(MARGIN, pdf.get_y(), pdf.w - MARGIN, pdf.get_y())
        pdf.ln(8)

        # Summary content
        pdf.set_font("Helvetica", size=10)
        for line in summary_text.split('\n'):
            if line.strip():
                pdf.multi_cell(w, 6, _safe(line))
                pdf.ln(2)

        # Footer
        pdf.ln(6)
        pdf.set_draw_color(102, 126, 234)
        pdf.line(MARGIN, pdf.get_y(), pdf.w - MARGIN, pdf.get_y())
        pdf.ln(5)
        pdf.set_font("Helvetica", 'I', 8)
        pdf.cell(w, 5, _safe("Generated by AI PDF Summarizer"), align='C')

        # fpdf2 returns bytearray; convert to bytes for Streamlit
        output = pdf.output()
        return bytes(output)

    
    @staticmethod
    def create_txt(summary_text, title="Summary", summary_type="", metadata=None):
        """
        Create formatted text file
        
        Args:
            summary_text (str): Summary content
            title (str): Document title
            summary_type (str): Type of summary
            metadata (dict): Additional metadata
            
        Returns:
            str: Formatted text content
        """
        lines = []
        lines.append("=" * 70)
        lines.append("AI-GENERATED SUMMARY")
        lines.append("=" * 70)
        lines.append("")
        
        if title:
            lines.append(f"Document: {title}")
            lines.append("")
        
        if summary_type:
            lines.append(f"Summary Type: {summary_type}")
            lines.append("")
        
        if metadata:
            lines.append("-" * 70)
            if 'model' in metadata:
                lines.append(f"AI Model: {metadata['model']}")
            if 'date' in metadata:
                lines.append(f"Generated: {metadata['date']}")
            if 'original_words' in metadata:
                lines.append(f"Original Words: {metadata['original_words']:,}")
            if 'summary_words' in metadata:
                lines.append(f"Summary Words: {metadata['summary_words']:,}")
            if 'compression' in metadata:
                lines.append(f"Compression Ratio: {metadata['compression']:.1f}%")
            lines.append("-" * 70)
            lines.append("")
        
        lines.append("SUMMARY:")
        lines.append("")
        lines.append(summary_text)
        lines.append("")
        lines.append("=" * 70)
        lines.append("Generated by AI PDF Summarizer")
        lines.append("=" * 70)
        
        return "\n".join(lines)
    
    @staticmethod
    def create_markdown(summary_text, title="Summary", summary_type="", metadata=None):
        """
        Create Markdown formatted summary
        
        Args:
            summary_text (str): Summary content
            title (str): Document title
            summary_type (str): Type of summary
            metadata (dict): Additional metadata
            
        Returns:
            str: Markdown formatted content
        """
        lines = []
        lines.append(f"# {title}")
        lines.append("")
        
        if summary_type:
            lines.append(f"**Summary Type:** {summary_type}")
            lines.append("")
        
        if metadata:
            lines.append("## Metadata")
            lines.append("")
            if 'model' in metadata:
                lines.append(f"- **AI Model:** {metadata['model']}")
            if 'date' in metadata:
                lines.append(f"- **Generated:** {metadata['date']}")
            if 'original_words' in metadata:
                lines.append(f"- **Original Words:** {metadata['original_words']:,}")
            if 'summary_words' in metadata:
                lines.append(f"- **Summary Words:** {metadata['summary_words']:,}")
            if 'compression' in metadata:
                lines.append(f"- **Compression:** {metadata['compression']:.1f}%")
            lines.append("")
        
        lines.append("## Summary")
        lines.append("")
        lines.append(summary_text)
        lines.append("")
        lines.append("---")
        lines.append("*Generated by AI PDF Summarizer*")
        
        return "\n".join(lines)