"""
Summary Exporter Module
File: backend/exporter.py
Description: Export summaries to various formats
"""

from fpdf import FPDF
from datetime import datetime


class SummaryExporter:
    """Export summaries to different formats"""
    
    @staticmethod
    def create_pdf(summary_text, title="Summary", summary_type="", metadata=None):
        """
        Create PDF file from summary text
        
        Args:
            summary_text (str): Summary content
            title (str): Document title
            summary_type (str): Type of summary
            metadata (dict): Additional metadata
            
        Returns:
            bytes: PDF file content
        """
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "AI-Generated Summary", ln=True, align='C')
        pdf.ln(5)
        
        # Summary type
        if summary_type:
            pdf.set_font("Arial", 'I', 12)
            pdf.cell(0, 10, f"Type: {summary_type}", ln=True, align='C')
            pdf.ln(5)
        
        # Document title
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, title, ln=True)
        pdf.ln(5)
        
        # Metadata
        if metadata:
            pdf.set_font("Arial", 'I', 10)
            if 'model' in metadata:
                pdf.cell(0, 8, f"AI Model: {metadata['model']}", ln=True)
            if 'date' in metadata:
                pdf.cell(0, 8, f"Generated: {metadata['date']}", ln=True)
            if 'compression' in metadata:
                pdf.cell(0, 8, f"Compression Ratio: {metadata['compression']:.1f}%", ln=True)
            pdf.ln(5)
        
        # Divider
        pdf.set_draw_color(102, 126, 234)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(10)
        
        # Summary content
        pdf.set_font("Arial", size=11)
        for line in summary_text.split('\n'):
            if line.strip():
                # Handle special characters
                clean_line = line.encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(0, 8, clean_line)
        
        # Footer
        pdf.ln(10)
        pdf.set_draw_color(102, 126, 234)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        pdf.set_font("Arial", 'I', 8)
        pdf.cell(0, 5, "Generated by AI PDF Summarizer", ln=True, align='C')
        
        return pdf.output(dest='S').encode('latin-1')
    
    @staticmethod
    def create_txt(summary_text, title="Summary", summary_type="", metadata=None):
        """
        Create formatted text file
        
        Args:
            summary_text (str): Summary content
            title (str): Document title
            summary_type (str): Type of summary
            metadata (dict): Additional metadata
            
        Returns:
            str: Formatted text content
        """
        lines = []
        lines.append("=" * 70)
        lines.append("AI-GENERATED SUMMARY")
        lines.append("=" * 70)
        lines.append("")
        
        if title:
            lines.append(f"Document: {title}")
            lines.append("")
        
        if summary_type:
            lines.append(f"Summary Type: {summary_type}")
            lines.append("")
        
        if metadata:
            lines.append("-" * 70)
            if 'model' in metadata:
                lines.append(f"AI Model: {metadata['model']}")
            if 'date' in metadata:
                lines.append(f"Generated: {metadata['date']}")
            if 'original_words' in metadata:
                lines.append(f"Original Words: {metadata['original_words']:,}")
            if 'summary_words' in metadata:
                lines.append(f"Summary Words: {metadata['summary_words']:,}")
            if 'compression' in metadata:
                lines.append(f"Compression Ratio: {metadata['compression']:.1f}%")
            lines.append("-" * 70)
            lines.append("")
        
        lines.append("SUMMARY:")
        lines.append("")
        lines.append(summary_text)
        lines.append("")
        lines.append("=" * 70)
        lines.append("Generated by AI PDF Summarizer")
        lines.append("=" * 70)
        
        return "\n".join(lines)
    
    @staticmethod
    def create_markdown(summary_text, title="Summary", summary_type="", metadata=None):
        """
        Create Markdown formatted summary
        
        Args:
            summary_text (str): Summary content
            title (str): Document title
            summary_type (str): Type of summary
            metadata (dict): Additional metadata
            
        Returns:
            str: Markdown formatted content
        """
        lines = []
        lines.append(f"# {title}")
        lines.append("")
        
        if summary_type:
            lines.append(f"**Summary Type:** {summary_type}")
            lines.append("")
        
        if metadata:
            lines.append("## Metadata")
            lines.append("")
            if 'model' in metadata:
                lines.append(f"- **AI Model:** {metadata['model']}")
            if 'date' in metadata:
                lines.append(f"- **Generated:** {metadata['date']}")
            if 'original_words' in metadata:
                lines.append(f"- **Original Words:** {metadata['original_words']:,}")
            if 'summary_words' in metadata:
                lines.append(f"- **Summary Words:** {metadata['summary_words']:,}")
            if 'compression' in metadata:
                lines.append(f"- **Compression:** {metadata['compression']:.1f}%")
            lines.append("")
        
        lines.append("## Summary")
        lines.append("")
        lines.append(summary_text)
        lines.append("")
        lines.append("---")
        lines.append("*Generated by AI PDF Summarizer*")
        
        return "\n".join(lines)
